Add a component to share Strava activities
PaulieScanlon/gatsby-mdx-embed pull request #42
Opened 2020-08-10 17:13 UTC by mbifulco

## Description

This PR introduces a `<Strava>` component, which allows the sharing of Strava activities from the embed code they provide on their site.

For some reason, Strava's embed code isn't straightforward enough to be fully predictable - IE you can't just pluck an activity ID and predict the rest of the embed URL.  It looks like there's some sort of hash appended to embed URLs, which is required for the iframe to work.  Because of that, the component needs the entire URL provided.  Some more (slightly unsatisfying) context [here](https://support.strava.com/hc/en-us/community/posts/208859027-Easily-obtainable-embed-URL).

With the exception of setting width to 100%, all of the props on the iframe come from the defaults provided by Strava:
![image](https://user-images.githubusercontent.com/1844496/89810585-4e1f0380-db0b-11ea-8122-339d3ff24b01.png)

## Related Issues
I created the PR before the issue - but see https://twitter.com/irreverentmike/status/1292846177994649601

2020-08-10 17:22 UTC, mbifulco commented
If you need to test, this is a _different_ embed code than the one I used for all of the samples in the PR:

```html
<iframe height='405' width='590' frameborder='0' allowtransparency='true' scrolling='no' src='https://www.strava.com/activities/3814929161/embed/92c108deebbe15f33f0d723486ebc3cc68fc14c0'></iframe>
```

2020-08-10 17:22 UTC, spences10 commented
Cool! I'll let @PaulieScanlon do the review but from my cursory look you need to update the `strava.stories.mdx` file to reflect the Strava component and it's still showing the Spotify header and importing the Spotify component.

To run the docs use `yarn develop:docs` and test there 🙏

2020-08-10 17:32 UTC, mbifulco commented
Great catch - thanks @spences10! 

![image](https://user-images.githubusercontent.com/1844496/89812308-e9b17380-db0d-11ea-9f9b-096798d6e898.png)

2020-08-10 17:37 UTC, spences10 commented
> Great catch - thanks @spences10!
> 
> ![image](https://user-images.githubusercontent.com/1844496/89812308-e9b17380-db0d-11ea-9f9b-096798d6e898.png)

Can you set the width on the map there? Doesn't appear to be 100% width? Or is that how it should be rendered?

2020-08-10 17:42 UTC, mbifulco commented
Unfortunately the map width is set by Strava. There's [community requests](https://support.strava.com/hc/en-us/community/posts/212747567-Embed-for-activity-widget-and-individual-activities-should-be-responsive) to make this component responsive, but they've been unanswered.

As a middleground, I can set a `maxWidth` of `590px` (strava's default for this embed), which might be a decent middleground - it'll just get cut off on mobile viewports, rather than overflow in the X direction.

![image](https://user-images.githubusercontent.com/1844496/89813209-537e4d00-db0f-11ea-8a67-82dd6c2f1ea3.png)

2020-08-10 17:51 UTC, spences10 commented
> Unfortunately the map width is set by Strava. There's [community requests](https://support.strava.com/hc/en-us/community/posts/212747567-Embed-for-activity-widget-and-individual-activities-should-be-responsive) to make this component responsive, but they've been unanswered.
> 
> As a middleground, I can set a `maxWidth` of `590px` (strava's default for this embed), which might be a decent middleground - it'll just get cut off on mobile viewports, rather than overflow in the X direction.
> 

Ok, I think it's good to go but I'll let @PaulieScanlon have his say.

2020-08-11 08:19 UTC, PaulieScanlon reviewed
Hey, and thanks for the PR. Would you be able to provide some more example of embed URL's. These embeds can be tricky for sure but i'm intrigued by what the differences in the urls would be and what effect they have on the rendered component.

2020-08-11 12:58 UTC, mbifulco commented
Hi @PaulieScanlon - no problem.  I'm only able to generate embed URLs from my own activities on Strava, but here's a few, organized by activity type:

### bicycle
1. https://www.strava.com/activities/3814929161/embed/92c108deebbe15f33f0d723486ebc3cc68fc14c0
1. https://www.strava.com/activities/3873020161/embed/60ded6a06e0b0ca43a3d75a9cf3d3bc5b0468461

### hiking
1. https://www.strava.com/activities/3828237836/embed/7af4c2d2d779de3e1fdf47fd77dc5f127bb2464e
1. https://www.strava.com/activities/1628527152/embed/1ff055cf71261b0df890c96acb9e3bcb02821ed9

### walking
1. https://www.strava.com/activities/3807860119/embed/ce635c68d084eddb52159fdf3fe0f90edb3f5a01
1.https://www.strava.com/activities/3804679697/embed/aa5238f5ceb3c005f7677b0fd4b0ddca1f58d0ee

### running
1. https://www.strava.com/activities/1109062121/embed/3ac9ab4839442215247c40aa1a0d527d39dc470c
1. https://www.strava.com/activities/878325127/embed/3955ac85ade1a882dd0abde872cd65d45f98e88f

### virtual ride (indoor bicycle)
1. https://www.strava.com/activities/3211681165/embed/bf157c409dc69d7619aadc47f7eba6294146b9db
1. https://www.strava.com/activities/3009002132/embed/e039b0ee68c99fdbde38c789b5af4e18b06c0c5d

2020-08-11 18:41 UTC, PaulieScanlon commented
@mbifulco Thanks for the links!  

I can see the difficulty here. 

On one had we could just do what you've done and have the url passed as a prop, on the other we could extract just the bits we need eg: 

`3211681165/embed/bf157c409dc69d7619aadc47f7eba6294146b9db` 

making this part hardcoded in the component: `https://www.strava.com/activities` 

... which would keep it inline with how we're doing everything else. 

I'm kind of torn between consistency and what makes sense for usage.


What do you think @spences10 ?

2020-08-11 18:50 UTC, mbifulco commented
@PaulieScanlon I had that same debate when I was cobbling this together - to me, the challenge is what to call that embed substring, as it's not particularly straightforward to name _or_ explain 🤔 

I wish Strava would make this a bit simpler - something tells me that last string is a hash of some sort to make sure that _only_ the user who owns the activity can derive share links for their stuff.

2020-08-11 18:56 UTC, PaulieScanlon commented
@mbifulco Hey! All those links work for me so i'm assuming if it's using their `embed` api they'll all be public?

We could call it `activityId` unless there's other Strava urls that are't related to activities?  in which case we might need to investigate a bit more.

2020-08-11 19:16 UTC, spences10 commented
> What do you think @spences10 ?

Think we should go with consistency, yas

2020-08-11 19:16 UTC, mbifulco commented
As far as I know, you can only share an activity with this type of embed. It seems misleading to call this property `activityId` though, because it requires that extra hash at the end. I think that may lead folks to try to share _just_ the activity ID that they see at the end of the URL on Strava - but I may be overthinking it.

2020-08-11 19:32 UTC, PaulieScanlon commented
@mbifulco That's a fair comment and the more of these we do the more differences and tricky one off's we're un-earthing. This lib is still in the patch versions `v.0.0.25` for that very reason. I wanted to see how different all these embeds might be and how we might consolidate the differences before moving to a stable `v1.0.0` 

I agree that perhaps sometimes the prop can be a little misleading and we have tried to explain how to use each component in the [help stories](https://gatsby-mdx-embed.netlify.app/?path=/docs/help--page#soundcloud) and so far we've not had any complaints regarding what props are called.

I think for the moment for better or worse i'd lean towards the `activityId` approach purely because it's more consistent with how everything else works but it's great that this has come up and we do have all of this think about before moving forward.

2020-08-11 20:35 UTC, mbifulco commented
You got it.  I'll push those changes soon

2020-08-12 14:42 UTC, mbifulco commented
all set!

2020-08-13 20:33 UTC, PaulieScanlon requested changes

2020-08-13 20:33 UTC, PaulieScanlon commented on docs/src/a-pages/3.help.stories.mdx
> +<Strava activityId="https://www.strava.com/activities/3857744534/embed/063fb45ce16095ff076c485ef6b14a01bf0e10e1" />
Hey mate, should this be:

```javascript
<Strava activityId="3857744534/embed/063fb45ce16095ff076c485ef6b14a01bf0e10e1" />
```

2020-08-13 20:33 UTC, PaulieScanlon commented on docs/src/components/strava.stories.mdx
> +  <Strava activityId="https://www.strava.com/activities/3857744534/embed/063fb45ce16095ff076c485ef6b14a01bf0e10e1" />
same as above here i think

```javascript
<Strava activityId="3857744534/embed/063fb45ce16095ff076c485ef6b14a01bf0e10e1" />

```

2020-08-13 20:33 UTC, PaulieScanlon commented on @pauliescanlon/gatsby-mdx-embed/src/components/Strava/Strava.tsx
> +  /** The activity ID provided by Strava's share action on the activity page.  Just the text after `https://www.strava.com/activities/`, which should look something like `1234567/embed/abcdefgh` */
Try to keep these description short as they appear in the Storybook prop table.

Maybe just say "activityId part of the url"... the help docs and code snippets help users work out the rest.

2020-08-14 13:54 UTC, mbifulco commented on docs/src/a-pages/3.help.stories.mdx
> +<Strava activityId="https://www.strava.com/activities/3857744534/embed/063fb45ce16095ff076c485ef6b14a01bf0e10e1" />
Oops! Working on these now.

2020-08-14 14:10 UTC, mbifulco commented
Alright @PaulieScanlon, one more try :)

2020-08-14 15:04 UTC, PaulieScanlon approved these changes

2020-08-14 15:05 UTC, PaulieScanlon commented
@mbifulco Approve mate! Thanks so much for this. I'll get it merged and released later tonight!

2020-08-19 13:52 UTC, merged